### ISSUE TITLE
add darkGrey and other avh4/elm-color colors 

### ISSUE THREAD

**Issue by bburdette** [escherlies/elm-color#1]
Looks like these are missing, there's just black and white:

    , red, orange, yellow, green, blue, purple, brown
    , lightRed, lightOrange, lightYellow, lightGreen, lightBlue, lightPurple, lightBrown
    , darkRed, darkOrange, darkYellow, darkGreen, darkBlue, darkPurple, darkBrown
    , white, lightGrey, grey, darkGrey, lightCharcoal, charcoal, darkCharcoal, black
    , lightGray, gray, darkGray

would be nice to have these as my code that uses avh4/elm-color depends on them.

**Comment by escherlies** [comment]
Hi @bburdette!

Thank you for this consideration!

I personally recommend creating your own module where you define these colors.
You could copy/paste them from avh4/elm-color, put them into their own module and use them along side this new library.

The reason is simply that I did not want to include any specific, subjective colors in this library but instead wanted to focus only on the abstractions.

Let me know if you are running into any other issues.

Best
